export * from './log.module';
export * from './log.service';
import * as winston2 from 'winston';
export const winston = winston2;
export {
  Container,
  ExceptionHandler,
  Logform,
  Logger,
  Profiler,
  RejectionHandler,
  add,
  addColors,
  child,
  clear,
  config,
  configure,
  createLogger,
  debug,
  error,
  exceptions,
  exitOnError,
  format,
  http,
  info,
  level,
  log,
  loggers,
  profile,
  query,
  rejections,
  remove,
  silly,
  startTimer,
  stream,
  transport,
  transports,
  verbose,
  version,
  warn,
} from 'winston';
